server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wsdb}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_POSSWORD:postgres}
